name: Publish Node Package

on:
    push: 
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./node-package

        steps: 
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with: 
                node-version: 20
                registry-url: 'https://npm.pkg.github.com'
                scope: "@smartcloud2023"

            - name: Install dependencies
              run: npm install 

            - name: Build package
              run: npm run build  

            - name: Publish package now
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}


            - name: Read package version
              id: package
              run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
            
            - name: Create GitHub Release
              env:
                 GH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
                 inputs.version: ${{ steps.package.outputs.version }}
              run: |
                    curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer $GH_TOKEN" \
                    -H "X-GitHub-Api-Version: 2026-03-10" \
                    https://api.github.com/repos/${{ github.repository }}/releases \
                    -d '{
                        "tag_name": "v${{ steps.package.outputs.version }}",
                        "target_commitish": "main",
                        "name": "smartmath-node v${{ steps.package.outputs.version }}",
                        "body": "smartmath-node v${{ steps.package.outputs.version }}",
                        "draft": false,
                        "prerelease": false,
                        "generate_release_notes": true
                    }'
            # - name: Create GitHub Release
            #   uses: softprops/action-gh-release@v2
            #   with:
            #     tag_name: "v${{ inputs.version }}"
            #     name: "v${{ steps.package.outputs.version }}"
            #     body: |
            #         ## smartmath-node v${{ steps.package.outputs.version }}

            #         Node.js package published to GitHub Packages.

            #         ### Installation

            #         ```bash
            #         npm install @smartcloud2023/smartmath-node
            #         ```
            #     files: |
            #         node-package/*.tgz
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}